name: Rust

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install minimal stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      run: cargo +stable build --verbose
    - name: Check
      run: cargo +stable check --verbose
    - name: Test
      run: cargo +stable test --verbose

